global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory-service:3001']

  - job_name: 'customers-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['customers-service:3002']

  - job_name: 'sales-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sales-service:3003']
